### ISSUE TITLE
Drop bomb option is greyed out

### ISSUE THREAD

**Issue by rovicomm** [wchamilton/CEManeuverLog#19]
![image](https://github.com/user-attachments/assets/062de725-daa6-428b-9f2e-4462a85fd5f5)

Bomb selection is unable to be selected at any point in the mission.

This is on the Albatros C-1 plane.

**Comment by wchamilton** [comment]
Turns out this was due to an error in the plane file, the crew wasn't set up as capable of dropping bombs. Closing.
